# Generated by Django 4.2.4 on 2023-09-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_artist_profile_picture1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_profile',
            name='picture2',
            field=models.ImageField(default='default.png', upload_to='artist_pic/'),
        ),
        migrations.AlterField(
            model_name='artist_profile',
            name='picture3',
            field=models.ImageField(default='default.png', upload_to='artist_pic/'),
        ),
    ]
