# Generated by Django 4.2.4 on 2023-09-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_artist_profile_picture2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_profile',
            name='artist_fees',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
